import { Contact } from "./types";

const now = new Date().toISOString();

// Helper to keep seed defs compact
function c(
  id: string,
  tier: Contact["tier"],
  category: Contact["category"],
  organization: string,
  subOrg: string,
  contactName: string,
  title: string,
  email: string,
  phone: string,
  linkedin: string,
  orgUrl: string,
  location: string,
  dealSize: string,
  outreachHook: string,
  owner: Contact["owner"],
  notes: string,
  source: string,
  nextAction: string = ""
): Contact {
  return {
    id,
    tier,
    category,
    organization,
    subOrg,
    contactName,
    title,
    email,
    phone,
    linkedin,
    orgUrl,
    location,
    dealSize,
    status: "Not Started",
    firstTouch: "",
    lastTouch: "",
    touches: 0,
    nextAction,
    nextActionDate: "",
    outreachHook,
    owner,
    notes,
    source,
    createdAt: now,
    updatedAt: now,
  };
}

export const SEED_CONTACTS: Contact[] = [
  // ─── APEX Accelerators ───
  c("e-001", "Tier 1", "APEX Accelerator",
    "Women's Business Development Center (Illinois APEX)", "Illinois — Chicago",
    "Donna Beasley", "Director, Government Contracting / Center Director, Illinois APEX",
    "dbeasley@wbdc.org", "(312) 853-3477",
    "https://www.linkedin.com/in/donnabeasley/",
    "https://www.wbdc.org/en/programs-and-services/il-apex-accelerator/",
    "Chicago, IL", "$50K-$68K",
    "ACTIVE QUOTE in market — memo notes Donna received OpenGovIQ quote at $50K-$68K. We are the more complete product. Lead with: 'You priced this. Let me show you why we're the better answer at the same number.' Direct connection: Darryl Thomas (NAPEX ED) is the FORMER Illinois APEX state director — Donna's boss for years.",
    "Eric",
    "Per memo: highest-priority active opportunity. Eric should own.",
    "Mindy Enterprise.docx",
    "Send re-engagement email referencing OpenGovIQ quote"),

  c("e-002", "Tier 1", "APEX Accelerator",
    "National APEX Accelerator Alliance (NAPEX)", "HQ — National",
    "Darryl Thomas", "Executive Director",
    "", "",
    "https://www.linkedin.com/in/darryl-thomas-60099064/",
    "https://www.napex.us/",
    "Springfield, IL (HQ DC)", "$150K+",
    "First-ever NAPEX ED (started 2025). Came directly from Illinois APEX where Donna Beasley still works. If we win Illinois we win the NAPEX intro. Pitch: 'Power the entire 96-center network with the Deltek alternative your members can actually afford.' This is the unlock — 1 deal = entire network.",
    "Eric",
    "Strategic — federation play. Pursue AFTER Illinois pilot is in motion to have proof.",
    "napex.us",
    "Research email; book intro call"),

  c("e-003", "Tier 1", "APEX Accelerator",
    "National APEX Accelerator Alliance (NAPEX)", "Board — President",
    "Frank Dixon", "President, NAPEX / State Director, Virgin Islands APEX",
    "", "", "",
    "https://www.napex.us/",
    "St. Thomas, USVI", "$100K+",
    "NAPEX President. Army veteran, decorated. UVI-affiliated. Strong angle: serving territories often underserved by Deltek. Combined approach with Darryl Thomas could land a federation-level conversation.",
    "Eric",
    "Pair with Darryl Thomas outreach.",
    "uvi.edu / napex.us",
    "Research email; reference UVI affiliation"),

  c("e-004", "Tier 1", "APEX Accelerator",
    "Virginia APEX Accelerator at George Mason University", "Virginia — Fairfax",
    "", "Statewide Director",
    "apex@gmu.edu", "(703) 277-7700", "",
    "https://virginiaapex.org/",
    "Fairfax, VA", "$50K-$75K",
    "108 jurisdictions in VA — high density of federal contractors due to DoD/IC proximity. Sponsored by George Mason. Generic apex@gmu.edu confirmed; named contact still TBD. Highest-volume APEX center in the country by client base.",
    "Branden",
    "Need to identify named director before personalizing.",
    "virginiaapex.org",
    "Identify named director via LinkedIn before sending"),

  c("e-005", "Tier 1", "APEX Accelerator",
    "Champaign County EDC (Illinois APEX)", "Illinois — Champaign",
    "Keli Krueger-Huhra, MBA, CPSM", "Director, Illinois APEX Accelerator at Champaign County EDC",
    "", "", "",
    "https://cusbdc.org/government-contracting/",
    "Champaign, IL", "$25K-$35K",
    "Secondary IL center — Donna Beasley's network. Smaller territory but use as pilot proof-point if main Chicago center stalls.",
    "Branden",
    "Backup play to main Donna Beasley conversation.",
    "cusbdc.org",
    "Reach via LinkedIn; secondary IL play"),

  c("e-006", "Tier 2", "APEX Accelerator",
    "Arkansas APEX Accelerator", "Arkansas — Statewide",
    "Melanie Berman", "Program Director / NAPEX Board Secretary",
    "", "", "",
    "https://www.napex.us/",
    "Little Rock, AR", "$25K-$50K",
    "20+ yrs in econ dev. NAPEX board secretary — well-networked nationally. Win her, win second federation advocate after Darryl.",
    "Branden",
    "Strong board-level reference if won.",
    "napex2025.vfairs.com",
    "Research email + LinkedIn"),

  c("e-007", "Tier 2", "APEX Accelerator",
    "Louisiana APEX Accelerator at U. Louisiana-Lafayette", "Louisiana — Region 8",
    "Cindy Carrier", "Program Manager / NAPEX Region 8 Director",
    "", "", "",
    "https://www.napex.us/",
    "Lafayette, LA", "$25K-$50K",
    "Award-winning center (NAPEX Outstanding Project Award 2022). Covers AR/LA/NM/OK/TX — 5-state regional director. Win her = 5 states of warm intros.",
    "Branden",
    "Regional director influence is multi-state leverage.",
    "napex2025.vfairs.com",
    "Research email + LinkedIn"),

  // ─── Veteran Member Associations ───
  c("e-008", "Tier 1", "Veteran Member Association",
    "National Veteran Small Business Coalition (NVSBC)", "HQ",
    "Scott Jensen", "Chief Executive Officer",
    "", "",
    "https://www.linkedin.com/in/scottjensen269/",
    "https://nvsbc.org/",
    "Washington, DC", "$75K-$150K",
    "35,000+ veteran-owned small biz members. NVSBC just helped raise the veteran small biz federal goal from 3% to 5% — legislative win. VETS conference (Orlando) = 200+ qualified prospects in one room. Member-benefit play: white-label MI as included perk. Naval Academy, Marine Corps veteran.",
    "Eric",
    "Top of veteran association list.",
    "nvsbc.org",
    "Research email; pitch member-benefit model"),

  c("e-009", "Tier 1", "Veteran Member Association",
    "National Veteran-Owned Business Association (NaVOBA)", "HQ",
    "Matthew Pavelek", "President & CEO",
    "matthew.pavelek@navoba.org", "(412) 477-3218",
    "https://www.linkedin.com/in/matthew-pavelek-1798b927/",
    "https://www.navoba.org/",
    "Lexington, KY", "$50K-$100K",
    "Corporate-supplier-diversity focused (Fortune 1000), but members are VBEs/SDVBEs hunting federal contracts. Verified email. CEO since 2006 — stable, accessible. Joint Forces Forum (Oct) is a sponsorship lever.",
    "Eric",
    "Verified email available — strongest first-touch candidate in veteran category.",
    "RocketReach / navoba.org",
    "Send intro email — verified contact"),

  // ─── SBDCs ───
  c("e-010", "Tier 1", "SBDC",
    "America's SBDC (Association of SBDCs)", "National Association",
    "Charles \"Tee\" Rowe", "President / CEO",
    "tee.rowe@americassbdc.org", "",
    "https://www.linkedin.com/in/c-e-tee-rowe-b683391/",
    "https://americassbdc.org/",
    "Washington, DC", "$150K+",
    "REPRESENTS 1,000 SBDC CENTERS NATIONWIDE. Former SBA Associate Administrator (Congressional Affairs). 20+ yrs at America's SBDC. Verified email. Federation play: license MI to America's SBDC, deploy to member network. One contract = potential 1,000 centers.",
    "Eric",
    "Highest leverage single-target in entire workbook. National federation deal.",
    "americassbdc.org",
    "Send intro email — verified contact"),

  c("e-011", "Tier 2", "SBDC",
    "America's SBDC", "VP",
    "April Youngblut", "Vice President",
    "april@americassbdc.org", "", "",
    "https://americassbdc.org/",
    "Washington, DC", "$150K+",
    "Tee's #2. Often the actual gatekeeper for partnership conversations at trade associations. Verified email.",
    "Eric",
    "Pair with Tee Rowe outreach.",
    "americassbdc.org",
    "Cc on Tee Rowe outreach"),

  c("e-012", "Tier 2", "SBDC",
    "America's SBDC", "Membership",
    "Brett Thibodeau", "Director of Membership Services",
    "brett@americassbdc.org", "", "",
    "https://americassbdc.org/",
    "Washington, DC", "$50K-$100K",
    "Owns member-benefits programs. If federation deal too big to start, member-benefit add-on is a smaller surface-area sale.",
    "Branden",
    "Alternative entry path if Rowe/Youngblut slow.",
    "americassbdc.org",
    "Pitch: member-benefit / partner directory inclusion"),

  // ─── VBOCs ───
  c("e-013", "Tier 1", "VBOC",
    "South Carolina VBOC (The Citadel)", "South Carolina",
    "CJ Williams", "VBOC Program Director",
    "cwilli55@citadel.edu", "", "",
    "https://www.citadel.edu/business/sc-vboc/",
    "Charleston, SC", "$25K-$35K",
    "SC has top-10 per-capita veteran population (~400K). Citadel-hosted, opened May 2023 — newer center, exceeding all baseline KPIs. Mark Rosenbaum (mrosenba@citadel.edu) is Principal Investigator.",
    "Branden",
    "Smaller deal but easier sale — newer center, hungry for tools.",
    "citadel.edu",
    "Send intro email — verified contact"),

  c("e-014", "Tier 1", "VBOC",
    "McNulty Center VBOC (NY/NJ)", "New York / New Jersey",
    "Amy Amoroso", "Director",
    "aamoroso@mcnultycenter.org", "(518) 326-6328", "",
    "https://vbocregion2.com/",
    "Watervliet, NY", "$25K-$35K",
    "Verified email + direct phone. Two-state coverage (NY/NJ) = larger member base than typical VBOC.",
    "Branden",
    "Verified contact, ready to go.",
    "vbocregion2.com",
    "Send intro email — verified contact"),

  c("e-015", "Tier 2", "VBOC",
    "VBOC at Fayetteville State University", "North Carolina",
    "", "Director",
    "", "", "",
    "https://www.fsuvboc.com/",
    "Fayetteville, NC", "$25K-$35K",
    "Fort Bragg adjacency = highest density of transitioning service members in the country. NC veteran population is significant.",
    "Branden",
    "Geographic gold mine — needs name research.",
    "fsuvboc.com",
    "Identify named director; Fayetteville = Fort Bragg adjacency"),

  c("e-016", "Tier 2", "VBOC",
    "VBOC at Georgia Southern (GA/SC region)", "Georgia / South Carolina",
    "Jeremy Horstman", "Director",
    "", "", "", "",
    "Statesboro, GA area", "$25K-$35K",
    "Georgia Southern-affiliated. New director (Horstman) — fresh in role often means open to new tools.",
    "Branden",
    "Cross-check vs SC VBOC at Citadel — may be related.",
    "georgiasouthern.edu",
    "Research email — Georgia Southern affiliate"),

  // ─── WOSB ───
  c("e-017", "Tier 1", "WOSB Association",
    "Women Impacting Public Policy (WIPP)", "HQ",
    "Candace Waterman", "President & CEO",
    "", "", "",
    "https://www.wipp.org/",
    "Washington, DC", "$50K-$100K",
    "35+ years experience. Former VP/Chief of Staff at WBENC — owned the WOSB cert program. Now CEO at WIPP. Deep federal policy network. WIPP advocates for women entrepreneurs at federal level — direct mission match.",
    "Eric",
    "Strong fit. Has WBENC bridge built in.",
    "wbenc.org / wipp.org",
    "Research email; pitch federal contracting member benefit"),

  c("e-018", "Tier 2", "WOSB Association",
    "Women Impacting Public Policy (WIPP)", "Operations",
    "LaTonia Pouncey", "Senior staff",
    "", "", "",
    "https://www.wipp.org/",
    "Washington, DC", "$50K-$100K",
    "Mentioned in recent WBENC NY DMV summit coverage as visible WIPP leadership figure.",
    "Branden",
    "Supporting cast.",
    "wbecnydmv.org",
    "Cc on Waterman outreach"),

  // ─── Trade Associations ───
  c("e-019", "Tier 1", "Trade Association",
    "AFCEA International", "HQ",
    "Lt. Gen. Susan S. Lawrence (Ret.)", "Outgoing President & CEO (until June 2026)",
    "", "", "",
    "https://www.afcea.org/",
    "Fairfax, VA", "$100K+",
    "BREAKING TIMING: Bruce Crawford incoming as 12th CEO June 2026. First African American to lead AFCEA. Lawrence retiring. Perfect inflection: pitch a 'new chapter' partnership as he takes over. 30,000 members across military/govt/industry — strongest C4ISR/defense IT trade association in country.",
    "Eric",
    "FLAGGED: Pitch the transition. Email Crawford via AFCEA after June 15 effective date.",
    "globenewswire.com (Apr 2026)",
    "TIMING WINDOW: Lawrence retiring June 2026 — pitch incoming CEO"),

  c("e-020", "Tier 1", "Trade Association",
    "AFCEA International", "Incoming CEO",
    "Lt. Gen. Bruce Crawford (Ret.)", "Incoming President & CEO (eff. June 15, 2026)",
    "", "", "",
    "https://www.afcea.org/",
    "Fairfax, VA", "$100K+",
    "Currently AFCEA Vice Chair (since May 2025), Budget & Finance Committee Chair. Becoming 12th AFCEA CEO June 2026. 'New leader, new partnership' framing is wide open. Army Lt. Gen. retired.",
    "Eric",
    "DATE-DEPENDENT: Hold outreach until 6/15/26 effective date.",
    "globenewswire.com",
    "Send welcome / partnership intro AFTER June 15"),

  c("e-021", "Tier 2", "Trade Association",
    "NCMA (National Contract Management Association)", "Board of Advisors",
    "Various", "Board of Advisors (80 senior executives)",
    "", "", "",
    "https://ncmahq.org/",
    "Ashburn, VA", "$50K-$100K",
    "Contract management profession HQ. Board includes Booz Allen, Raytheon, IBM, SAIC, Parsons heads of contracts. NCMA conferences attract every federal CO and KO. Need to ID named CEO.",
    "Branden",
    "Different angle — they manage contracts vs. find them. Soft fit. Lower priority.",
    "ncmahq.org",
    "Identify CEO name; pitch contract management vertical"),

  // ─── Tribal 8(a) ───
  c("e-022", "Tier 1", "Tribal 8(a)",
    "Native American Contractors Association (NACA)", "HQ",
    "Quinton Carroll", "Executive Director",
    "", "", "",
    "https://nativecontractors.org/",
    "Washington, DC", "$100K+",
    "Inupiat Community of Arctic Slope tribal member. Represents Tribes, ANCs, Native Hawaiian Orgs nationally. $23.3B in tribal federal contracts in 2023 (16% YoY surge). ANCs lead with 2/3 of the increase. Sole-source 8(a) cap raised from $20M to $100M. Massive market.",
    "Eric",
    "Cultural sensitivity required — refer to Eric for relationship approach.",
    "nativecontractors.org / indianz.com",
    "Research email; pitch member-benefit / federal intel"),

  c("e-023", "Tier 1", "Tribal 8(a)",
    "Native American Contractors Association (NACA)", "Co-Chair",
    "Katherine Carlton", "Co-Chair NACA / SVP Chugach Corporation",
    "", "", "",
    "https://nativecontractors.org/",
    "Anchorage, AK", "$100K+",
    "Chugach shareholder. Harvard B-School AMP. Oversees ANCSA lands & community development. Strong technical + business leader.",
    "Eric",
    "Pair with Quinton Carroll outreach.",
    "nativecontractors.org",
    "LinkedIn intro; reference Chugach federal work"),

  c("e-024", "Tier 1", "Tribal 8(a)",
    "Native American Contractors Association (NACA)", "Co-Chair",
    "Jon Deacon Panamaroff", "Co-Chair NACA / CEO Command Holdings (Pequot Co.)",
    "", "", "",
    "https://nativecontractors.org/",
    "Washington, DC area", "$100K+",
    "CEO of Command Holdings (Pequot tribe company). Hosted SBA Administrator Guzman fireside at NACA conf. Sitting at the table with federal leadership.",
    "Eric",
    "High-influence executive; warm introduction preferred over cold.",
    "linkedin.com/company/native-american-contractors-association",
    "LinkedIn intro; reference Command Holdings federal work"),

  c("e-025", "Tier 2", "Tribal 8(a)",
    "Alaska Native Village Corporation Association (ANVCA)", "HQ",
    "Shyanne Beatty", "Communications Consultant (entry point)",
    "shyanne@anvca.biz", "", "",
    "https://anvca.biz/",
    "Anchorage, AK", "$75K-$150K",
    "176 village corporations + 12 regional corporations. Annual symposium = audience of federal-contracting CEOs. Shyanne Beatty (comms consultant) is named, accessible contact for routing.",
    "Branden",
    "Massive aggregate market but requires cultural-fit care.",
    "anvca.biz / linkedin",
    "Email Shyanne Beatty for routing"),

  // ─── Existing customers ───
  c("e-026", "Tier 1", "Existing Customer",
    "Encore Funding", "Existing relationship",
    "", "Founder / CEO",
    "", "", "", "",
    "TBD", "$75K-$100K",
    "EXISTING: Per memo, contributing to $11,767/mo revenue together w/ White Glove. Already paying near enterprise pricing. Expansion opp: add-on services, more seats, custom briefing development. Don't re-sell — UPSELL.",
    "Eric",
    "Eric owns the relationship. Reference memo for revenue context.",
    "Mindy Enterprise.docx",
    "Schedule quarterly expansion review"),

  c("e-027", "Tier 1", "Existing Customer",
    "White Glove Client", "Existing relationship",
    "", "Decision-maker",
    "", "", "", "",
    "TBD", "$75K-$100K",
    "EXISTING: Co-contributor to $141K/yr revenue base. Same upsell logic as Encore.",
    "Eric",
    "Eric owns. Real org name redacted in memo.",
    "Mindy Enterprise.docx",
    "Schedule quarterly expansion review"),

  // ─── Channel ───
  c("e-028", "Channel", "Channel Partner",
    "[GovCon consulting firms — research list]", "Multiple",
    "", "Founding partners",
    "", "", "", "",
    "Various", "Referral",
    "Channel play: consultants/lawyers/CPAs whose clients all need MI. They become referral partners. Revenue share or affinity discount. Lower priority than direct enterprise sales but compounds over time.",
    "Branden",
    "Long-term play. Build list once direct pipeline is moving.",
    "Mindy Enterprise.docx",
    "Build target list of 10-15 boutique GovCon consultancies"),

  // ─── APEX Accelerators — May 2026 nationwide directory expansion ───
  // Source: research/apex-contacts-may2026.md
  // Skipped as already in seed: Donna Beasley (e-001), Darryl Thomas (e-002),
  // Frank Dixon (e-003), Virginia APEX/GMU (e-004), Melanie Berman (e-006),
  // Cindy Carrier (e-007).

  // — NAPEX leadership (officers — Tier 1) —
  c("e-029", "Tier 1", "APEX Accelerator",
    "Ohio APEX Accelerator (statewide)", "Ohio — Columbus HQ",
    "Joey Scott", "Statewide Program Manager / NAPEX President-Elect",
    "", "(614) 644-1637", "",
    "https://apex.ohio.edu/",
    "Columbus, OH (77 S High St, 28th Fl)", "$100K+",
    "HIGH-LEVERAGE DUAL PLAY. Statewide PM for one of the largest APEX networks (sub-centers at OU, YSU, Lakeland CC, U Toledo, NW State CC, Cleveland, Dayton). ALSO NAPEX President-Elect — federation-level influence. Pitch: enterprise OH deployment + NAPEX endorsement.",
    "Eric",
    "Federation pilot candidate — pair with Darryl Thomas outreach.",
    "research/apex-contacts-may2026.md",
    "Research email; pitch statewide + NAPEX pilot"),

  c("e-030", "Tier 1", "APEX Accelerator",
    "Iowa APEX Accelerator", "Iowa — Statewide",
    "Jodi Essex", "Program Director / NAPEX Immediate Past President",
    "", "", "",
    "https://www.iowaeda.com/",
    "Des Moines, IA", "$75K-$150K",
    "CPP-certified. NAPEX immediate past president — sustained board reference voice. Strong validator for new vendor decisions network-wide.",
    "Eric",
    "NAPEX board reference voice.",
    "research/apex-contacts-may2026.md",
    "Research email; reference NAPEX past-president role"),

  c("e-031", "Tier 1", "APEX Accelerator",
    "Empire APEX Accelerator", "New York — Cattaraugus County area",
    "Lenora Leasure", "Program Manager / NAPEX Vice President",
    "", "", "",
    "https://www.empireapex.org/",
    "Cattaraugus County, NY", "$75K-$150K",
    "HIGH-PRIORITY HOOK: Promoted to PM Aug 2024 (within 18-month tech-stack reassessment window) AND serves as NAPEX VP. CPP/MBA. Pitch: congrats on promotion + ready-made enterprise tool.",
    "Eric",
    "TRANSITION WINDOW — promoted Aug 2024; dual NAPEX VP leverage.",
    "research/apex-contacts-may2026.md",
    "Send intro: reference promotion + NAPEX VP role"),

  c("e-032", "Tier 1", "APEX Accelerator",
    "Southern Alleghenies APEX", "Pennsylvania — Altoona / 18-county region",
    "James Gerraughty", "Program Manager / NAPEX Treasurer",
    "", "", "",
    "https://www.napex.us/",
    "Altoona, PA", "$75K-$150K",
    "NAPEX Treasurer (officer) — sees national vendor-spend P&L. CPP/MBA. 18-county central-PA region, 4 centers.",
    "Eric",
    "Officer-level outreach; treasurer view of NAPEX vendor spend.",
    "research/apex-contacts-may2026.md",
    "Research email; pitch NAPEX vendor partnership"),

  // — Tier 1 multi-office states (FL, OH, TX, IN, KY, MI) —
  c("e-033", "Tier 1", "APEX Accelerator",
    "Florida APEX Accelerator (statewide)", "Florida — University of West Florida (host)",
    "Jessica Tenney", "Statewide Program Manager",
    "", "", "",
    "https://www.flapex.org/",
    "Pensacola, FL", "$100K+",
    "Statewide FL network: UWF, FAU, FGCU, UCF, USF, UNF, IRSC, FIU, FAMU, Pinellas. Potential 10+ user enterprise deployment via single statewide decision-maker.",
    "Eric",
    "Highest seat-count single decision-maker in FL.",
    "research/apex-contacts-may2026.md",
    "Research email; pitch network-wide deployment"),

  c("e-034", "Tier 1", "APEX Accelerator",
    "Cross Timbers APEX (UT Arlington)", "Texas — Fort Worth / North TX",
    "Lori Manning", "Program Manager / State Director",
    "", "(817) 272-5978",
    "https://www.linkedin.com/in/lori-manning/",
    "https://www.uta.edu/academics/schools-colleges/business/centers/cross-timbers-apex",
    "Fort Worth, TX (7300 Jack Newell Blvd S #116)", "$100K+",
    "STAR PERFORMER: Grew Cross Timbers awards from $167M (2024) to $1.57B (2025) — nearly 10x. Former Idaho APEX state director. Vocal NAPEX networker; her referral opens multi-state doors.",
    "Eric",
    "BUDGET + INFLUENCE: massive growth = budget; multi-state referral power.",
    "research/apex-contacts-may2026.md",
    "Send intro email; reference $167M→$1.57B growth"),

  c("e-035", "Tier 1", "APEX Accelerator",
    "Indiana APEX Accelerator", "Indiana — Statewide",
    "Dannielle Yelder", "Program Manager / State Director",
    "", "", "",
    "https://inapex.org/",
    "Indianapolis, IN (IEDC)", "$75K-$150K",
    "Statewide network covers all 92 counties via 6 regional offices. Host: Indiana Economic Development Corporation. Chris Jeffers is VP of Defense Business Development. Single-decision-maker for 6-region deploy.",
    "Branden",
    "Statewide single-stakeholder enterprise opportunity.",
    "research/apex-contacts-may2026.md",
    "Research email; pitch 6-region enterprise"),

  c("e-036", "Tier 1", "APEX Accelerator",
    "Kentucky APEX Accelerator", "Kentucky — Statewide (7 offices)",
    "Nancy Brown", "Executive Director",
    "", "", "",
    "https://www.kyapex.com/",
    "Frankfort, KY", "$75K-$150K",
    "Single Executive Director oversees 7 statewide offices — clean enterprise deal. KY hosts Fort Campbell + Fort Knox = federal contracting density.",
    "Branden",
    "Clean single-stakeholder enterprise deal.",
    "research/apex-contacts-may2026.md",
    "Research email; pitch 7-office enterprise"),

  c("e-037", "Tier 1", "APEX Accelerator",
    "Schoolcraft College APEX (Michigan)", "Michigan — Metro Detroit",
    "Olga Martinez", "Program Administrator / NAPEX Region 6 Director / NAPEX Strategy Chair",
    "", "", "",
    "https://www.miapex.org/",
    "Livonia, MI (Schoolcraft College)", "$75K-$150K",
    "NAPEX Region 6 Director (5-state region) + Strategy Chair. Michigan APEX Alliance is multi-host (Schoolcraft, Wayne State APEX@wayne.edu (313) 577-0132, Networks Northwest); Schoolcraft is the lead.",
    "Branden",
    "Region 6 multi-state influence; MI Alliance entry point.",
    "research/apex-contacts-may2026.md",
    "Research email; pitch MI Alliance + Region 6"),

  c("e-038", "Tier 1", "APEX Accelerator",
    "NYC SBS APEX Accelerator", "New York — NYC (city agency)",
    "Rogina Coar-Smith", "Executive Director",
    "APEXAccelerator@sbs.nyc.gov", "(212) 513-6444", "",
    "https://nyc-business.nyc.gov/",
    "New York, NY", "$75K-$150K",
    "Newly named Executive Director at the largest city-level APEX in the US. NYC SBS budget is city-funded — different procurement cycle than state APEXs.",
    "Eric",
    "HIGH-PRIORITY: new ED + city procurement = atypical buying motion.",
    "research/apex-contacts-may2026.md",
    "Send intro via APEXAccelerator@sbs.nyc.gov"),

  // — Tier 2 standard state programs —
  c("e-039", "Tier 2", "APEX Accelerator",
    "Alabama APEX Accelerator", "Alabama — University of Alabama",
    "Brian Davis", "AITC Director / State Lead",
    "", "(205) 348-1687", "",
    "https://apexal.org/",
    "Tuscaloosa, AL (Box 870396)", "$50K-$75K",
    "Host: UA Office for Research. Sub-centers at Jacksonville State (George Williams, Venessa Noel), UNA (Phillip Marks).",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "Research email; reference AITC role"),

  c("e-040", "Tier 3", "APEX Accelerator",
    "Alaska APEX Accelerator", "Alaska — UAA",
    "Carolyn Pratt", "Program Manager",
    "capratt@alaska.edu", "(907) 786-7258", "",
    "https://apexalaska.org/",
    "Anchorage, AK (1901 Bragaw St Rm 199)", "$25K-$35K",
    "Host: University of Alaska Anchorage, Business Enterprise Institute. Also: Jody King (jlking8@alaska.edu, Asst Dir); Pierre Thompson (Fairbanks, pdthompson@alaska.edu). General: info@apexalaska.org.",
    "Branden",
    "Verified email.",
    "research/apex-contacts-may2026.md",
    "Send intro email — verified contact"),

  c("e-041", "Tier 2", "APEX Accelerator",
    "Arizona APEX Accelerator", "Arizona — Maricopa Community Colleges",
    "Lori Haozous", "Program Manager / State Director",
    "", "(623) 845-4700", "",
    "https://arizonaapex.org/",
    "Queen Creek, AZ (21740 S Ellsworth Rd)", "$50K-$75K",
    "Host: Maricopa Community Colleges (Communiversity at Queen Creek) — NOT Arizona Commerce Authority.",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "Research email; LinkedIn intro"),

  c("e-042", "Tier 2", "APEX Accelerator",
    "AICEF APEX (American Indian Chamber Education Fund)", "Multi-state Tribal — CA/AZ/NV/UT/OR/WA/ID (Pacific/Western/NW BIA Regions)",
    "Venessa Gleich", "Program Manager / NAPEX Region 11 Director",
    "", "", "",
    "https://aicef-apex.org/",
    "Sacramento, CA area", "$50K-$100K",
    "Tribal APEX serving 197 tribes/reservations across 7 western states. NAPEX Region 11 Director. Multi-state influence — significant aggregate addressable market.",
    "Eric",
    "Cultural sensitivity required — Eric leads tribal approach.",
    "research/apex-contacts-may2026.md",
    "Eric to lead; reference 197-tribe service area"),

  c("e-043", "Tier 2", "APEX Accelerator",
    "NCAIED APEX (National Center for American Indian Enterprise Dev)", "Multi-state Tribal — 61 tribes / 33 states (Eastern, Southwest, Navajo BIA)",
    "George Williams", "Program Manager",
    "", "", "",
    "https://ncaied.org/",
    "Marietta, GA (HQ) + AZ/CO/NM/LA/NY satellites", "$50K-$100K",
    "VERIFY BEFORE OUTREACH: Project Director Joan Begay Notah passed away May 2026 per NCAIED site — confirm current Project Director before sending.",
    "Eric",
    "Verify current leadership before outreach.",
    "research/apex-contacts-may2026.md",
    "Confirm current Project Director before outreach"),

  c("e-044", "Tier 2", "APEX Accelerator",
    "California Capital APEX Accelerator", "California — Sacramento",
    "Chuck Jehle", "Procurement Consultant",
    "", "", "",
    "https://cacapital.org/",
    "Sacramento, CA", "$25K-$50K",
    "Sacramento-region APEX. One of several CA regional centers (no single state lead).",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "LinkedIn intro"),

  c("e-045", "Tier 2", "APEX Accelerator",
    "Inland Empire APEX Accelerator", "California — Riverside / San Bernardino",
    "Valorie Piper", "Director, MBA",
    "", "",
    "https://www.linkedin.com/in/valorie-piper-mba-60241115/",
    "https://www.rccd.edu/",
    "Riverside, CA (Riverside CCD)", "$25K-$50K",
    "LinkedIn confirmed. SoCal regional center.",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "LinkedIn intro"),

  c("e-046", "Tier 2", "APEX Accelerator",
    "San Diego, Orange & Imperial APEX Accelerator", "California — SoCal Region 10",
    "Mike Sabellico", "Regional Director / NAPEX Region 10 Director",
    "", "", "",
    "https://www.napex.us/",
    "San Diego, CA", "$50K-$75K",
    "20-yr USCG veteran. Covers 3 SoCal counties. NAPEX Region 10 Director — multi-state referral angle.",
    "Branden",
    "Veteran framing for first-touch.",
    "research/apex-contacts-may2026.md",
    "Research email; veteran framing"),

  c("e-047", "Tier 2", "APEX Accelerator",
    "Colorado APEX Accelerator", "Colorado — Colorado Springs HQ",
    "Patrick McGlew", "Program Manager / Co-State Director",
    "", "(719) 431-8028", "",
    "https://www.coloradoapex.org/",
    "Colorado Springs, CO (310 S 14th St)", "$50K-$75K",
    "Co-led with Beth Taylor. Affiliated with Minority Business Office at Colorado OEDIT (state matching). Sr Procurement Counselors incl. John Papile (LinkedIn confirmed), Metzler, Kidd, Gunning, Thompson, Fuller, Martinez.",
    "Branden",
    "Dual-PM org — pitch both leads.",
    "research/apex-contacts-may2026.md",
    "Research emails for McGlew + Taylor"),

  c("e-048", "Tier 2", "APEX Accelerator",
    "Connecticut APEX Accelerator", "Connecticut — Groton",
    "Marisol Herrera", "State Director (MSM, CPP)",
    "info@ctapex.org", "(860) 437-4659", "",
    "https://ctapex.org/",
    "Groton, CT (19-B Thames St)", "$50K-$75K",
    "WARM-INTRO ANGLE: Frank Dixon (NAPEX President, USVI APEX) is a former CT APEX Program Manager — leverage him for intro. Vice Chair NERC Engagement & Strategic Initiatives.",
    "Branden",
    "Pair with Frank Dixon outreach for warm-intro path.",
    "research/apex-contacts-may2026.md",
    "Send intro via info@ctapex.org; reference Dixon connection"),

  c("e-049", "Tier 2", "APEX Accelerator",
    "Georgia APEX Accelerator (GT APEX)", "Georgia — Georgia Tech",
    "Nancy Cleveland", "Statewide Program Manager",
    "nancy.cleveland@innovate.gatech.edu", "", "",
    "https://gtapexaccelerator.org/",
    "Atlanta, GA (Georgia Tech EI²)", "$50K-$75K",
    "Host: Georgia Tech Enterprise Innovation Institute. Verified email.",
    "Branden",
    "Verified email.",
    "research/apex-contacts-may2026.md",
    "Send intro email — verified contact"),

  c("e-050", "Tier 2", "APEX Accelerator",
    "Kansas APEX Accelerator", "Kansas — Wichita State",
    "Terri Bennett", "Program Manager / State Director",
    "", "", "",
    "https://www.wichita.edu/research/kansasapexaccelerator/",
    "Wichita, KS (WSU)", "$25K-$50K",
    "Host: Wichita State University + JCCC sub-center (Christina Lawson, Overland Park, (913) 469-2313). Wichita HQ staff: Julian Gonzalez-Salamanca, Scott Knapp, Kristi Dunn (Topeka).",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "Research email"),

  c("e-051", "Tier 2", "APEX Accelerator",
    "Minnesota APEX Accelerator", "Minnesota — St. Paul",
    "Christina Nebel-Dickerson", "Program Director",
    "christina.nebel-dickerson@state.mn.us", "(651) 201-2629", "",
    "https://mn.gov/admin/business/",
    "St. Paul, MN (50 Sherburne Ave Ste 112)", "$50K-$75K",
    "Host: MN Dept of Administration. NAPEX locator separately lists Denise Warner as PM — possible dual-leader; verify roles.",
    "Branden",
    "Verified email; clarify Nebel-Dickerson vs Warner roles.",
    "research/apex-contacts-may2026.md",
    "Send intro email — verified contact"),

  c("e-052", "Tier 2", "APEX Accelerator",
    "Mississippi APEX Accelerator", "Mississippi — Statewide (7 regional centers)",
    "Carol Harris", "MDA Director of Minority and Small Business / APEX Director",
    "", "", "",
    "https://msapexaccelerator.org/",
    "Jackson, MS (MDA)", "$50K-$75K",
    "Host: Mississippi Development Authority. 7 regional centers (Gulfport, Columbus, Cleveland, Meridian, Jackson + satellites in Tupelo & Hattiesburg). Comms contact: Joycie Lenoir (jlenoir@mississippi.org).",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "Research email; route via jlenoir@mississippi.org"),

  c("e-053", "Tier 2", "APEX Accelerator",
    "Missouri APEX Accelerator", "Missouri — SW MO (Springfield/Joplin)",
    "Allen Waldo", "Regional Specialist, CPP / NAPEX Ballots Chair",
    "", "", "",
    "https://extension.missouri.edu/programs/apex-accelerator",
    "Springfield, MO area", "$25K-$50K",
    "Host: University of Missouri Extension (statewide network). Multiple regional specialists incl. Jason Cole (UMKC; Wyandotte Nation).",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "Research email; reference NAPEX Ballots Chair"),

  c("e-054", "Tier 2", "APEX Accelerator",
    "Nebraska APEX Accelerator", "Nebraska — UNO College of Business",
    "Chuck Beck", "Regional/State Director, CPP / NAPEX Region 7 Director",
    "", "", "",
    "https://www.unomaha.edu/",
    "Omaha, NE (UNO)", "$25K-$50K",
    "Helped establish NAPEX National Training program. NAPEX Region 7 Director (multi-state).",
    "Branden",
    "Region 7 multi-state referral potential.",
    "research/apex-contacts-may2026.md",
    "Research email; reference NAPEX Region 7"),

  c("e-055", "Tier 2", "APEX Accelerator",
    "Nevada APEX Accelerator", "Nevada — GOED",
    "Nathan Jackson", "Deputy Director",
    "", "",
    "https://www.linkedin.com/in/nathan-jackson-57974544/",
    "https://goed.nv.gov/programs/nevada-apex-accelerator/",
    "Las Vegas / Carson City, NV", "$25K-$50K",
    "Host: NV Governor's Office of Economic Development. EXPANSION SIGNAL: Govt Contracts Advisor opening posted early 2026 — staffing-up = active budget cycle.",
    "Branden",
    "Hiring signal = active budget.",
    "research/apex-contacts-may2026.md",
    "LinkedIn intro; reference hiring expansion"),

  c("e-056", "Tier 2", "APEX Accelerator",
    "NJIT APEX Accelerator", "New Jersey — NJIT",
    "Hailey Park", "Statewide Director",
    "", "",
    "https://www.linkedin.com/in/hailey-park-6050a7197/",
    "https://www.njit.edu/apex",
    "Newark, NJ (NJIT) + Camden sub-office", "$50K-$75K",
    "Host: New Jersey Institute of Technology. LinkedIn confirmed.",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "LinkedIn intro"),

  c("e-057", "Tier 2", "APEX Accelerator",
    "New Mexico APEX Accelerator", "New Mexico — Santa Fe",
    "Therese Rivera", "Statewide Program Manager",
    "therese.rivera@sfcc.edu", "(505) 428-1374", "",
    "https://www.nmapexaccelerator.org/",
    "Santa Fe, NM (6401 Richards Ave)", "$25K-$50K",
    "Host: Santa Fe Community College (with state matching). Associate PM: Martin Gutierrez. Verified email + phone.",
    "Branden",
    "Verified contact.",
    "research/apex-contacts-may2026.md",
    "Send intro email — verified contact"),

  c("e-058", "Tier 2", "APEX Accelerator",
    "MCFL APEX Accelerator (Monroe/Genesee Finger Lakes)", "New York — Rochester area",
    "Anna Vulaj Fitzsimmons", "Program Director / NAPEX Region 2 Director",
    "", "", "",
    "https://www.napex.us/",
    "Irondequoit, NY", "$50K-$75K",
    "PD since 2015. Clients have secured $2.76B in contracts/subcontracts during her tenure — credible reference customer. NAPEX Region 2 Director (multi-state NE).",
    "Branden",
    "Region 2 multi-state referral + $2.76B reference impact.",
    "research/apex-contacts-may2026.md",
    "Research email; reference $2.76B impact"),

  c("e-059", "Tier 2", "APEX Accelerator",
    "North Carolina APEX Accelerator (NC SBTDC)", "North Carolina — Raleigh",
    "Byron Hicks", "State Executive Director, NC SBTDC (umbrella host)",
    "bhicks@sbtdc.org", "(919) 600-5920", "",
    "https://sbtdc.org/services/government-contracting/",
    "Raleigh, NC (701 Corporate Center Dr Ste 340)", "$50K-$75K",
    "SBTDC is the umbrella host (administers APEX on behalf of UNC System). Partner (not host): NC Military Business Center.",
    "Branden",
    "Verified email.",
    "research/apex-contacts-may2026.md",
    "Send intro email — verified contact"),

  c("e-060", "Tier 2", "APEX Accelerator",
    "Oklahoma APEX Accelerator (OkAPEX)", "Oklahoma — CareerTech",
    "Lana Knott", "Program Manager",
    "", "(405) 743-5122", "",
    "https://oklahoma.gov/careertech/business-and-industry/okapex.html",
    "Stillwater, OK (1500 W 7th Ave)", "$25K-$50K",
    "Host: OK Dept of Career and Technology Education (CareerTech), delivered via local Technology Centers. Outreach Coordinator: Shelley Dawson (405) 743-5571.",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "Research email"),

  c("e-061", "Tier 2", "APEX Accelerator",
    "Oregon APEX Accelerator (formerly GCAP)", "Oregon — Springfield",
    "Dee Edwards", "Program Manager / State Director",
    "", "(541) 736-1088", "",
    "https://www.orapexaccelerator.org/",
    "Springfield, OR (1144 Gateway Loop Ste 203)", "$25K-$50K",
    "Host: Organization for Economic Initiatives (OEI), admin since 1993. Eastern OR sub-counselor: Gary Moore (NAPEX Professional Review Chair, ex-Idaho PTAC PM).",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "Research email"),

  c("e-062", "Tier 2", "APEX Accelerator",
    "Southeast PA APEX (SEPA APEX)", "Pennsylvania — Kutztown University",
    "Beth Alboucq", "Program Manager / NAPEX Region 3 Director / NAPEX Bylaws Chair",
    "", "(484) 646-4244", "",
    "https://www.napex.us/",
    "Kutztown, PA (15200 Kutztown Rd, deFrancesco Bldg Ste 135)", "$50K-$75K",
    "NAPEX Region 3 Director + Bylaws Chair — committee-level board influence.",
    "Branden",
    "Region 3 + Bylaws Chair = board credibility.",
    "research/apex-contacts-may2026.md",
    "Research email; reference Region 3 + Bylaws"),

  c("e-063", "Tier 2", "APEX Accelerator",
    "South Carolina APEX Accelerator", "South Carolina — Columbia",
    "Ron Conner", "Statewide Program Manager / State Director",
    "", "(803) 521-2344", "",
    "https://www.napex.us/",
    "Columbia, SC (701 Assembly St Ste 4009)", "$50K-$75K",
    "Sr Procurement Counselor: Sarah DePeri. Counselors: Jasmine Kennedy, Reggie Turman, Cordeija Horne, Ashley Duwel.",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "Research email"),

  c("e-064", "Tier 2", "APEX Accelerator",
    "Tennessee APEX Accelerator", "Tennessee — UT CIS",
    "Jutta Bangs", "Senior Counselor / Cybersecurity Specialist / NAPEX Region 5 Director / NAPEX Communications Chair",
    "", "", "",
    "https://tnapex.tennessee.edu/",
    "Knoxville, TN (UT Center for Industrial Services)", "$50K-$75K",
    "Dual NAPEX board role (Region 5 + Communications Chair). Cybersecurity SME = angle for security/compliance value prop. Also: Jen Dangelo (Program Support; NAPEX Curriculum Chair).",
    "Branden",
    "Communications Chair = great reference path if won.",
    "research/apex-contacts-may2026.md",
    "Research email; cybersecurity angle"),

  c("e-065", "Tier 2", "APEX Accelerator",
    "Utah APEX Accelerator", "Utah — GOEO",
    "Chuck Spence", "Statewide Lead",
    "", "(801) 538-8655",
    "https://www.linkedin.com/in/chuck-spence-0501ba6/",
    "https://business.utah.gov/apex/",
    "Salt Lake City, UT (GOEO)", "$50K-$75K",
    "Long-time program leader; former APTAC President-Elect 2014. 7 statewide locations.",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "LinkedIn intro"),

  c("e-066", "Tier 2", "APEX Accelerator",
    "Wisconsin APEX Accelerator (WPI)", "Wisconsin — Milwaukee",
    "Aina Vilumsons", "President / Executive Director, Wisconsin Procurement Institute",
    "ainav@wispro.org", "(414) 270-3600",
    "https://www.linkedin.com/in/ainavilumsons",
    "https://www.wispro.org/",
    "Milwaukee, WI (10437 Innovation Dr Ste 320)", "$50K-$75K",
    "Host: Wisconsin Procurement Institute. General: ApexAccelerator@wispro.org. Verified email + phone + LinkedIn.",
    "Branden",
    "Verified contact.",
    "research/apex-contacts-may2026.md",
    "Send intro email — verified contact"),

  c("e-067", "Tier 2", "APEX Accelerator",
    "Massachusetts APEX Accelerator", "Massachusetts — UMass Lowell",
    "Michelle Simoes", "Procurement Specialist (UMass Lowell office)",
    "msimoes@umass.edu", "(978) 770-7450", "",
    "https://www.massapex.org/",
    "Lowell, MA", "$50K-$75K",
    "FUNDING-CYCLE FLAG: DoD reopened the cooperative-agreement competition for MA APEX in 2025 (Simpler.Grants.gov opp 357855). Post-recompete budget reset = vendor-friendly moment. Statewide director name not publicly confirmed.",
    "Branden",
    "TRANSITION WINDOW: post-recompete budget reset.",
    "research/apex-contacts-may2026.md",
    "Send intro to Simoes; monitor recompete announcement"),

  c("e-068", "Tier 2", "APEX Accelerator",
    "Joseph Center APEX (Illinois sub-center)", "Illinois — Forest Park",
    "Chris Hollingsworth", "Director / NAPEX Awards & Recognition Chair",
    "", "", "",
    "https://www.josephcenter.org/",
    "Forest Park, IL", "$25K-$50K",
    "Secondary Illinois APEX sub-center within the Donna Beasley statewide network. NAPEX Awards Chair = committee-level board reach.",
    "Branden",
    "Secondary IL play; not in conflict with main Beasley pursuit (e-001).",
    "research/apex-contacts-may2026.md",
    "Research email; NAPEX board angle"),

  c("e-069", "Tier 2", "APEX Accelerator",
    "Florida APEX Accelerator at Pinellas County EDC", "Florida — Pinellas County",
    "Yolanda Goodloe", "Gov't Contracting Consultant / NAPEX Region 4 Director / 2024 People's Choice Award",
    "", "", "",
    "https://www.flapex.org/",
    "Pinellas County, FL", "$25K-$50K",
    "NAPEX Region 4 Director (SE region). 2024 People's Choice award winner — visible profile within network.",
    "Branden",
    "Region 4 multi-state influence; recent award winner.",
    "research/apex-contacts-may2026.md",
    "Research email; reference 2024 award"),

  c("e-070", "Tier 2", "APEX Accelerator",
    "University of Houston APEX", "Texas — Houston",
    "Ram Ramaswamy", "Senior Procurement Advisor",
    "uhapex@central.uh.edu", "(832) 842-8477", "",
    "https://www.uhapex.uh.edu/",
    "Houston, TX (1455 West Loop South Ste 890)", "$50K-$75K",
    "Advisors: Rubina Daudpota, Dennis McIntosh, Marina Coryat, Tim Healy; Coordinator: Jessica Kilpatrick. General email verified. Pair with Cross Timbers (e-034) for two-deal TX play.",
    "Branden",
    "TX has no single state lead — pair with e-034 Cross Timbers.",
    "research/apex-contacts-may2026.md",
    "Send intro to uhapex@central.uh.edu"),

  // Ohio sub-centers (within Tier 1 OH program; sub-center deals = Tier 2)
  c("e-071", "Tier 2", "APEX Accelerator",
    "Ohio University APEX (Athens HQ)", "Ohio — Athens",
    "Sharon Hopkins", "Center Director",
    "hopkins1@ohio.edu", "(740) 597-1868", "",
    "https://apex.ohio.edu/",
    "Athens, OH", "$25K-$50K",
    "OU sub-center within Ohio APEX network. Verified email.",
    "Branden",
    "Verified email.",
    "research/apex-contacts-may2026.md",
    "Send intro email — verified contact"),

  c("e-072", "Tier 2", "APEX Accelerator",
    "Youngstown State University APEX", "Ohio — Youngstown",
    "Scot Loveland", "Center Director",
    "swloveland@ysu.edu", "(330) 941-2146", "",
    "https://apex.ohio.edu/",
    "Youngstown, OH (Williamson CBA)", "$25K-$50K",
    "YSU sub-center within Ohio APEX network. Verified email.",
    "Branden",
    "Verified email.",
    "research/apex-contacts-may2026.md",
    "Send intro email — verified contact"),

  c("e-073", "Tier 2", "APEX Accelerator",
    "Northeast Ohio APEX (Lakeland CC)", "Ohio — NE Ohio",
    "Jane Stewart", "Associate Director (NE Ohio)",
    "stewartj1@ohio.edu", "(440) 525-7733", "",
    "https://apex.ohio.edu/",
    "Lakeland CC, OH", "$25K-$50K",
    "Lakeland CC sub-center. Verified email.",
    "Branden",
    "Verified email.",
    "research/apex-contacts-may2026.md",
    "Send intro email — verified contact"),

  c("e-074", "Tier 2", "APEX Accelerator",
    "Central Ohio APEX (Cleveland)", "Ohio — Cleveland",
    "Karen Wivell", "Associate Director",
    "wivell@ohio.edu", "", "",
    "https://apex.ohio.edu/",
    "Cleveland, OH", "$25K-$50K",
    "Cleveland sub-center. Verified email.",
    "Branden",
    "Verified email.",
    "research/apex-contacts-may2026.md",
    "Send intro email — verified contact"),

  c("e-075", "Tier 2", "APEX Accelerator",
    "Southwest Ohio APEX (Dayton)", "Ohio — Dayton",
    "Billy Grill", "Associate Director (SW Ohio)",
    "bgrill@ohio.edu", "", "",
    "https://apex.ohio.edu/",
    "Dayton, OH", "$25K-$50K",
    "Dayton-area sub-center; WPAFB-adjacent (high DoD density). Verified email.",
    "Branden",
    "Verified email; WPAFB-area DoD density.",
    "research/apex-contacts-may2026.md",
    "Send intro email — verified contact"),

  c("e-076", "Tier 2", "APEX Accelerator",
    "Northwest State CC APEX (Van Wert)", "Ohio — NW Ohio",
    "Jeremy Garber", "Center Director",
    "", "", "",
    "https://apex.ohio.edu/",
    "Van Wert, OH", "$25K-$35K",
    "NW Ohio sub-center.",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "Research email"),

  c("e-077", "Tier 2", "APEX Accelerator",
    "University of Toledo APEX", "Ohio — Toledo",
    "Alissa Karg Girard", "Center Director",
    "alissa.karggirard@utoledo.edu", "", "",
    "https://apex.ohio.edu/",
    "Toledo, OH (U of Toledo)", "$25K-$50K",
    "U of Toledo sub-center. Verified email.",
    "Branden",
    "Verified email.",
    "research/apex-contacts-may2026.md",
    "Send intro email — verified contact"),

  // — Tier 3 territories + small states —
  c("e-078", "Tier 3", "APEX Accelerator",
    "Delaware APEX Accelerator", "Delaware — UD",
    "Walt Blaney", "Program Manager / State Director (Dr.)",
    "", "(302) 831-0780", "",
    "https://www.delawareapex.org/",
    "Newark, DE (591 Collaboration Way 2nd Fl)", "$25K-$35K",
    "Host: University of Delaware, Office of Economic Innovation & Partnerships (OEIP). Referenced as 'Walt Blaner' in some materials.",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "Research email"),

  c("e-079", "Tier 3", "APEX Accelerator",
    "DC APEX Accelerator", "DC — DSLBD",
    "Milton Goodman", "Program Director",
    "", "(202) 727-3900",
    "https://www.linkedin.com/in/milton-goodman-9412b110/",
    "https://dslbd.dc.gov/service/dc-apex-accelerator",
    "Washington, DC (441 4th St NW Ste 850 N)", "$25K-$35K",
    "Host: DC Dept of Small and Local Business Development. LinkedIn confirmed.",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "LinkedIn intro"),

  c("e-080", "Tier 3", "APEX Accelerator",
    "Guam APEX Accelerator", "Guam — U of Guam",
    "Boris Hertslet", "Program Manager / State Director",
    "", "(671) 735-2596", "",
    "https://guamapex.com/",
    "Mangilao, GU (UOG SBPA Rm 117)", "$25K-$35K",
    "Host: University of Guam, School of Business & Public Administration. Procurement counselors: Victoria Villanueva, Ignacia Barcinas. Also serves CNMI businesses (no standalone CNMI program).",
    "Branden",
    "Also services CNMI clients.",
    "research/apex-contacts-may2026.md",
    "Research email"),

  c("e-081", "Tier 3", "APEX Accelerator",
    "Hawaii APEX Accelerator (HI-PTAC)", "Hawaii — HTDC",
    "Joaquin Villarreal", "Program Manager",
    "", "(808) 784-3711", "",
    "https://www.hiptac.org/",
    "Honolulu, HI (677 Ala Moana Blvd Ste 612)", "$25K-$35K",
    "Host: Hawaii Technology Development Corporation (HTDC), attached to DBEDT. Other staff: Micolas Ogawa (micolas.ogawa@hiptac.org). Ext 109.",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "Research email; phone ext 109"),

  c("e-082", "Tier 3", "APEX Accelerator",
    "Idaho APEX Accelerator", "Idaho — IN HOST TRANSITION",
    "", "TBD — host transition in progress",
    "", "", "",
    "https://www.idahoapexaccelerator.com/",
    "Idaho", "$25K-$35K",
    "HIGH-PRIORITY WATCH: Currently transitioning to a new host org; new clients paused. Former state director Lori Manning is now Cross Timbers APEX TX (e-034). Outreach should coincide with the new host announcement.",
    "Branden",
    "TRANSITION WATCH: new host announcement = re-engage trigger.",
    "research/apex-contacts-may2026.md",
    "Monitor idahoapexaccelerator.com for new host"),

  c("e-083", "Tier 3", "APEX Accelerator",
    "Idaho APEX Accelerator (Panhandle / Region 9)", "Idaho — Rathdrum",
    "Beth Freeman Myers", "Senior APEX Consultant / NAPEX Region 9 Director",
    "", "", "",
    "https://www.idahoapexaccelerator.com/",
    "Rathdrum, ID", "$25K-$35K",
    "NAPEX Region 9 Director (multi-state NW influence). Likely retains regional role through ID host transition.",
    "Branden",
    "Region 9 multi-state value; stable through ID transition.",
    "research/apex-contacts-may2026.md",
    "Research email; NAPEX Region 9 angle"),

  c("e-084", "Tier 3", "APEX Accelerator",
    "Maine APEX Accelerator", "Maine — EMDC",
    "Miranda Pelkey", "Program Director (promoted May 2025)",
    "", "", "",
    "https://maineptac.org/",
    "Bangor, ME (EMDC)", "$25K-$35K",
    "HIGH-PRIORITY HOOK: Promoted from Deputy to Director May 2025 — within 12-month tech-stack reassessment window. NAPEX Education Committee Chair (June 2025). Host: Eastern Maine Development Corp (also partners w/ AVCOG).",
    "Branden",
    "NEW DIRECTOR WINDOW — first 12 months of role.",
    "research/apex-contacts-may2026.md",
    "Research email; reference promotion + Education Chair"),

  c("e-085", "Tier 2", "APEX Accelerator",
    "Maryland APEX Accelerator", "Maryland — UMD College Park",
    "", "Director (name not publicly surfaced)",
    "", "(301) 405-6550", "",
    "https://www.marylandapex.org/",
    "College Park, MD (5825 University Research Court Ste 1300)", "$50K-$75K",
    "Host: University of Maryland system (since 2002). Director name not surfaced in NAPEX locator — pull from team page directly.",
    "Branden",
    "Need to identify named director.",
    "research/apex-contacts-may2026.md",
    "Identify named director via marylandapex.org team page"),

  c("e-086", "Tier 3", "APEX Accelerator",
    "Montana APEX Accelerator", "Montana — Big Sky EDC, Billings",
    "Deanna Langman", "Statewide Director",
    "", "(406) 869-8414", "",
    "https://montanaapex.org/",
    "Billings, MT (201 N Broadway)", "$25K-$35K",
    "TRANSITION SIGNAL: Listed as Statewide Director on Who-We-Are page while Tereza Brownell (e-087) is listed as Interim Statewide Director on Locations page — suggests active transition. Verify role status before outreach.",
    "Branden",
    "TRANSITION FLAG: confirm role status before sending.",
    "research/apex-contacts-may2026.md",
    "Call (406) 869-8414 to verify role status"),

  c("e-087", "Tier 3", "APEX Accelerator",
    "Montana APEX Accelerator (Interim leadership)", "Montana — Big Sky EDC, Billings",
    "Tereza Brownell", "Interim Statewide Director",
    "tereza@bigskyeda.org", "(406) 869-8414", "",
    "https://montanaapex.org/",
    "Billings, MT", "$25K-$35K",
    "Listed as Interim Statewide Director on Locations page. If permanent appointment lands, that's a 12-month buying window.",
    "Branden",
    "INTERIM ROLE = upcoming permanent-appointment buying window.",
    "research/apex-contacts-may2026.md",
    "Send to tereza@bigskyeda.org"),

  c("e-088", "Tier 3", "APEX Accelerator",
    "New Hampshire APEX Accelerator", "New Hampshire — NH Dept of Business & Economic Affairs",
    "Dave Pease", "Senior Counselor / past Program Manager / NAPEX Stakeholders Chair",
    "", "", "",
    "https://www.nheconomy.com/",
    "Concord, NH", "$25K-$35K",
    "Pease managed program 2008–2023; now Senior Counselor + NAPEX Stakeholders Chair. Current PM not surfaced — confirm before outreach.",
    "Branden",
    "Confirm current PM; Pease still active as Sr Counselor.",
    "research/apex-contacts-may2026.md",
    "Research current PM; reach Pease via NAPEX role"),

  c("e-089", "Tier 3", "APEX Accelerator",
    "North Dakota APEX Accelerator", "North Dakota — UND",
    "David Kleppe", "Program Manager",
    "", "", "",
    "https://und.edu/ndapex",
    "Grand Forks, ND (UND)", "$25K-$35K",
    "Host: UND Nistler College of Business and Public Administration; state match from Bank of North Dakota. Also: Tiffany Ford (Director, CBED); Marnie Schuschke (Assoc State Director); Cadi Zerr (Procurement Specialist).",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "Research email"),

  c("e-090", "Tier 3", "APEX Accelerator",
    "Puerto Rico APEX Accelerator (Federal Contracting Center)", "Puerto Rico — DDEC",
    "Pedro Acevedo", "Program Manager / State Director",
    "", "(787) 758-4747", "",
    "https://federalcontracting.ddec.pr.gov/",
    "Hato Rey, PR (355 F.D. Roosevelt Ave Office 205)", "$25K-$35K",
    "Host: PR Dept of Economic Development and Commerce (DDEC). Ext 3181. Procurement Counselors: Rey Torres, Ada Santos, Adriana Acaron.",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "Research email; phone ext 3181"),

  c("e-091", "Tier 3", "APEX Accelerator",
    "Rhode Island APEX Accelerator (RI APEX)", "Rhode Island — RI Commerce Corp",
    "Chad Lewis", "Director / NAPEX Region 1 Director",
    "", "", "",
    "https://commerceri.com/apex-accelerator",
    "Providence, RI", "$25K-$35K",
    "US Navy veteran, ex-NAVSUP WSS contracting officer. NAPEX Region 1 Director (multi-state NE). Program Coordinator: Jake Bacon.",
    "Branden",
    "Region 1 multi-state + veteran first-touch angle.",
    "research/apex-contacts-may2026.md",
    "Research email; veteran framing"),

  c("e-092", "Tier 3", "APEX Accelerator",
    "South Dakota APEX Accelerator", "South Dakota — Pierre HQ",
    "", "Statewide Director (name not publicly confirmed)",
    "", "(605) 773-2753", "",
    "https://sdbusinesshelp.com/procurement-technical-assistance-center",
    "Pierre, SD (221 S. Central Ave Ste 33)", "$25K-$35K",
    "NAPEX locator shows placeholder data. Yankton sub-center: Jen Moser (Jen.Moser@districtiii.org, Planning & Development District III). Recommend calling HQ to confirm director.",
    "Branden",
    "Director name unconfirmed — call Pierre HQ.",
    "research/apex-contacts-may2026.md",
    "Call (605) 773-2753 to confirm director"),

  c("e-093", "Tier 3", "APEX Accelerator",
    "Vermont APEX Accelerator", "Vermont — VT ACCD",
    "Joanne Spaulding", "Director (since 2017) / NAPEX Regional Director / DoD NERC member",
    "ACCD.APEXinfo@vermont.gov", "(802) 828-5237", "",
    "https://accd.vermont.gov/economic-development/apex",
    "Montpelier, VT (1 National Life Drive Deane C Davis Bldg 6th Fl)", "$25K-$35K",
    "Host: VT Agency of Commerce and Community Development. Other staff: Denise Nelson (PA); Elizabeth Adams (Bennington/Rutland). General email verified.",
    "Branden",
    "General email confirmed.",
    "research/apex-contacts-may2026.md",
    "Send intro to ACCD.APEXinfo@vermont.gov"),

  c("e-094", "Tier 3", "APEX Accelerator",
    "West Virginia APEX Accelerator (RCAC)", "West Virginia — South Charleston",
    "", "Director (name not publicly displayed)",
    "", "", "https://www.linkedin.com/in/wvrcacptac/",
    "https://www.rcacwv.com/",
    "South Charleston, WV", "$25K-$35K",
    "Host: Regional Contracting Assistance Center, Inc. (RCAC) — non-profit (NOT WVU). Has held this role since 1987. Director name not on public pages — reach via contact form.",
    "Branden",
    "Director name unconfirmed — reach via contact form.",
    "research/apex-contacts-may2026.md",
    "Use contact form at rcacwv.com to identify director"),

  c("e-095", "Tier 3", "APEX Accelerator",
    "Wyoming APEX Accelerator", "Wyoming — Cheyenne",
    "Sarah Mikesell Growney", "Program Manager / State Director",
    "", "(307) 757-6869", "",
    "https://wyomingsbdc.org/team/sarah-mikesell-growney",
    "Cheyenne, WY (1400 E. College Dr)", "$25K-$35K",
    "Host: Wyoming SBDC Network. Program Assistant: Paul Johnson. HQ phone (307) 772-7372.",
    "Branden",
    "",
    "research/apex-contacts-may2026.md",
    "Research email"),

  c("e-096", "Tier 2", "APEX Accelerator",
    "Washington APEX Accelerator (Thurston EDC HQ)", "Washington — Statewide network",
    "", "Statewide Lead (name not publicly confirmed)",
    "", "", "",
    "https://washingtonapex.org/",
    "Thurston County, WA", "$50K-$75K",
    "Statewide lead: Thurston County Economic Development Council. 7 regional hosts (Kitsap EDA, Thurston EDC, Columbia River EDC, Economic Alliance Snohomish, Green River College, Greater Spokane Inc.). Multi-host coordination.",
    "Branden",
    "Multi-region; identify statewide lead via Thurston EDC.",
    "research/apex-contacts-may2026.md",
    "Contact Thurston EDC to identify statewide lead"),
];

// Mark existing customers as Nurture from the start
SEED_CONTACTS.forEach(c => {
  if (c.category === "Existing Customer") c.status = "Nurture";
});
