import { Contact } from "./types";

const now = new Date().toISOString();

// Helper to keep seed defs compact
function c(
  id: string,
  tier: Contact["tier"],
  category: Contact["category"],
  organization: string,
  subOrg: string,
  contactName: string,
  title: string,
  email: string,
  phone: string,
  linkedin: string,
  orgUrl: string,
  location: string,
  dealSize: string,
  outreachHook: string,
  owner: Contact["owner"],
  notes: string,
  source: string,
  nextAction: string = ""
): Contact {
  return {
    id,
    tier,
    category,
    organization,
    subOrg,
    contactName,
    title,
    email,
    phone,
    linkedin,
    orgUrl,
    location,
    dealSize,
    status: "Not Started",
    firstTouch: "",
    lastTouch: "",
    touches: 0,
    nextAction,
    nextActionDate: "",
    outreachHook,
    owner,
    notes,
    source,
    createdAt: now,
    updatedAt: now,
  };
}

export const SEED_CONTACTS: Contact[] = [
  // ─── APEX Accelerators ───
  c("e-001", "Tier 1", "APEX Accelerator",
    "Women's Business Development Center (Illinois APEX)", "Illinois — Chicago",
    "Donna Beasley", "Director, Government Contracting / Center Director, Illinois APEX",
    "dbeasley@wbdc.org", "(312) 853-3477",
    "https://www.linkedin.com/in/donnabeasley/",
    "https://www.wbdc.org/en/programs-and-services/il-apex-accelerator/",
    "Chicago, IL", "$50K-$68K",
    "ACTIVE QUOTE in market — memo notes Donna received OpenGovIQ quote at $50K-$68K. We are the more complete product. Lead with: 'You priced this. Let me show you why we're the better answer at the same number.' Direct connection: Darryl Thomas (NAPEX ED) is the FORMER Illinois APEX state director — Donna's boss for years.",
    "Eric",
    "Per memo: highest-priority active opportunity. Eric should own.",
    "Mindy Enterprise.docx",
    "Send re-engagement email referencing OpenGovIQ quote"),

  c("e-002", "Tier 1", "APEX Accelerator",
    "National APEX Accelerator Alliance (NAPEX)", "HQ — National",
    "Darryl Thomas", "Executive Director",
    "", "",
    "https://www.linkedin.com/in/darryl-thomas-60099064/",
    "https://www.napex.us/",
    "Springfield, IL (HQ DC)", "$150K+",
    "First-ever NAPEX ED (started 2025). Came directly from Illinois APEX where Donna Beasley still works. If we win Illinois we win the NAPEX intro. Pitch: 'Power the entire 96-center network with the Deltek alternative your members can actually afford.' This is the unlock — 1 deal = entire network.",
    "Eric",
    "Strategic — federation play. Pursue AFTER Illinois pilot is in motion to have proof.",
    "napex.us",
    "Research email; book intro call"),

  c("e-003", "Tier 1", "APEX Accelerator",
    "National APEX Accelerator Alliance (NAPEX)", "Board — President",
    "Frank Dixon", "President, NAPEX / State Director, Virgin Islands APEX",
    "", "", "",
    "https://www.napex.us/",
    "St. Thomas, USVI", "$100K+",
    "NAPEX President. Army veteran, decorated. UVI-affiliated. Strong angle: serving territories often underserved by Deltek. Combined approach with Darryl Thomas could land a federation-level conversation.",
    "Eric",
    "Pair with Darryl Thomas outreach.",
    "uvi.edu / napex.us",
    "Research email; reference UVI affiliation"),

  c("e-004", "Tier 1", "APEX Accelerator",
    "Virginia APEX Accelerator at George Mason University", "Virginia — Fairfax",
    "", "Statewide Director",
    "apex@gmu.edu", "(703) 277-7700", "",
    "https://virginiaapex.org/",
    "Fairfax, VA", "$50K-$75K",
    "108 jurisdictions in VA — high density of federal contractors due to DoD/IC proximity. Sponsored by George Mason. Generic apex@gmu.edu confirmed; named contact still TBD. Highest-volume APEX center in the country by client base.",
    "Branden",
    "Need to identify named director before personalizing.",
    "virginiaapex.org",
    "Identify named director via LinkedIn before sending"),

  c("e-005", "Tier 1", "APEX Accelerator",
    "Champaign County EDC (Illinois APEX)", "Illinois — Champaign",
    "Keli Krueger-Huhra, MBA, CPSM", "Director, Illinois APEX Accelerator at Champaign County EDC",
    "", "", "",
    "https://cusbdc.org/government-contracting/",
    "Champaign, IL", "$25K-$35K",
    "Secondary IL center — Donna Beasley's network. Smaller territory but use as pilot proof-point if main Chicago center stalls.",
    "Branden",
    "Backup play to main Donna Beasley conversation.",
    "cusbdc.org",
    "Reach via LinkedIn; secondary IL play"),

  c("e-006", "Tier 2", "APEX Accelerator",
    "Arkansas APEX Accelerator", "Arkansas — Statewide",
    "Melanie Berman", "Program Director / NAPEX Board Secretary",
    "", "", "",
    "https://www.napex.us/",
    "Little Rock, AR", "$25K-$50K",
    "20+ yrs in econ dev. NAPEX board secretary — well-networked nationally. Win her, win second federation advocate after Darryl.",
    "Branden",
    "Strong board-level reference if won.",
    "napex2025.vfairs.com",
    "Research email + LinkedIn"),

  c("e-007", "Tier 2", "APEX Accelerator",
    "Louisiana APEX Accelerator at U. Louisiana-Lafayette", "Louisiana — Region 8",
    "Cindy Carrier", "Program Manager / NAPEX Region 8 Director",
    "", "", "",
    "https://www.napex.us/",
    "Lafayette, LA", "$25K-$50K",
    "Award-winning center (NAPEX Outstanding Project Award 2022). Covers AR/LA/NM/OK/TX — 5-state regional director. Win her = 5 states of warm intros.",
    "Branden",
    "Regional director influence is multi-state leverage.",
    "napex2025.vfairs.com",
    "Research email + LinkedIn"),

  // ─── Veteran Member Associations ───
  c("e-008", "Tier 1", "Veteran Member Association",
    "National Veteran Small Business Coalition (NVSBC)", "HQ",
    "Scott Jensen", "Chief Executive Officer",
    "", "",
    "https://www.linkedin.com/in/scottjensen269/",
    "https://nvsbc.org/",
    "Washington, DC", "$75K-$150K",
    "35,000+ veteran-owned small biz members. NVSBC just helped raise the veteran small biz federal goal from 3% to 5% — legislative win. VETS conference (Orlando) = 200+ qualified prospects in one room. Member-benefit play: white-label MI as included perk. Naval Academy, Marine Corps veteran.",
    "Eric",
    "Top of veteran association list.",
    "nvsbc.org",
    "Research email; pitch member-benefit model"),

  c("e-009", "Tier 1", "Veteran Member Association",
    "National Veteran-Owned Business Association (NaVOBA)", "HQ",
    "Matthew Pavelek", "President & CEO",
    "matthew.pavelek@navoba.org", "(412) 477-3218",
    "https://www.linkedin.com/in/matthew-pavelek-1798b927/",
    "https://www.navoba.org/",
    "Lexington, KY", "$50K-$100K",
    "Corporate-supplier-diversity focused (Fortune 1000), but members are VBEs/SDVBEs hunting federal contracts. Verified email. CEO since 2006 — stable, accessible. Joint Forces Forum (Oct) is a sponsorship lever.",
    "Eric",
    "Verified email available — strongest first-touch candidate in veteran category.",
    "RocketReach / navoba.org",
    "Send intro email — verified contact"),

  // ─── SBDCs ───
  c("e-010", "Tier 1", "SBDC",
    "America's SBDC (Association of SBDCs)", "National Association",
    "Charles \"Tee\" Rowe", "President / CEO",
    "tee.rowe@americassbdc.org", "",
    "https://www.linkedin.com/in/c-e-tee-rowe-b683391/",
    "https://americassbdc.org/",
    "Washington, DC", "$150K+",
    "REPRESENTS 1,000 SBDC CENTERS NATIONWIDE. Former SBA Associate Administrator (Congressional Affairs). 20+ yrs at America's SBDC. Verified email. Federation play: license MI to America's SBDC, deploy to member network. One contract = potential 1,000 centers.",
    "Eric",
    "Highest leverage single-target in entire workbook. National federation deal.",
    "americassbdc.org",
    "Send intro email — verified contact"),

  c("e-011", "Tier 2", "SBDC",
    "America's SBDC", "VP",
    "April Youngblut", "Vice President",
    "april@americassbdc.org", "", "",
    "https://americassbdc.org/",
    "Washington, DC", "$150K+",
    "Tee's #2. Often the actual gatekeeper for partnership conversations at trade associations. Verified email.",
    "Eric",
    "Pair with Tee Rowe outreach.",
    "americassbdc.org",
    "Cc on Tee Rowe outreach"),

  c("e-012", "Tier 2", "SBDC",
    "America's SBDC", "Membership",
    "Brett Thibodeau", "Director of Membership Services",
    "brett@americassbdc.org", "", "",
    "https://americassbdc.org/",
    "Washington, DC", "$50K-$100K",
    "Owns member-benefits programs. If federation deal too big to start, member-benefit add-on is a smaller surface-area sale.",
    "Branden",
    "Alternative entry path if Rowe/Youngblut slow.",
    "americassbdc.org",
    "Pitch: member-benefit / partner directory inclusion"),

  // ─── VBOCs ───
  c("e-013", "Tier 1", "VBOC",
    "South Carolina VBOC (The Citadel)", "South Carolina",
    "CJ Williams", "VBOC Program Director",
    "cwilli55@citadel.edu", "", "",
    "https://www.citadel.edu/business/sc-vboc/",
    "Charleston, SC", "$25K-$35K",
    "SC has top-10 per-capita veteran population (~400K). Citadel-hosted, opened May 2023 — newer center, exceeding all baseline KPIs. Mark Rosenbaum (mrosenba@citadel.edu) is Principal Investigator.",
    "Branden",
    "Smaller deal but easier sale — newer center, hungry for tools.",
    "citadel.edu",
    "Send intro email — verified contact"),

  c("e-014", "Tier 1", "VBOC",
    "McNulty Center VBOC (NY/NJ)", "New York / New Jersey",
    "Amy Amoroso", "Director",
    "aamoroso@mcnultycenter.org", "(518) 326-6328", "",
    "https://vbocregion2.com/",
    "Watervliet, NY", "$25K-$35K",
    "Verified email + direct phone. Two-state coverage (NY/NJ) = larger member base than typical VBOC.",
    "Branden",
    "Verified contact, ready to go.",
    "vbocregion2.com",
    "Send intro email — verified contact"),

  c("e-015", "Tier 2", "VBOC",
    "VBOC at Fayetteville State University", "North Carolina",
    "", "Director",
    "", "", "",
    "https://www.fsuvboc.com/",
    "Fayetteville, NC", "$25K-$35K",
    "Fort Bragg adjacency = highest density of transitioning service members in the country. NC veteran population is significant.",
    "Branden",
    "Geographic gold mine — needs name research.",
    "fsuvboc.com",
    "Identify named director; Fayetteville = Fort Bragg adjacency"),

  c("e-016", "Tier 2", "VBOC",
    "VBOC at Georgia Southern (GA/SC region)", "Georgia / South Carolina",
    "Jeremy Horstman", "Director",
    "", "", "", "",
    "Statesboro, GA area", "$25K-$35K",
    "Georgia Southern-affiliated. New director (Horstman) — fresh in role often means open to new tools.",
    "Branden",
    "Cross-check vs SC VBOC at Citadel — may be related.",
    "georgiasouthern.edu",
    "Research email — Georgia Southern affiliate"),

  // ─── WOSB ───
  c("e-017", "Tier 1", "WOSB Association",
    "Women Impacting Public Policy (WIPP)", "HQ",
    "Candace Waterman", "President & CEO",
    "", "", "",
    "https://www.wipp.org/",
    "Washington, DC", "$50K-$100K",
    "35+ years experience. Former VP/Chief of Staff at WBENC — owned the WOSB cert program. Now CEO at WIPP. Deep federal policy network. WIPP advocates for women entrepreneurs at federal level — direct mission match.",
    "Eric",
    "Strong fit. Has WBENC bridge built in.",
    "wbenc.org / wipp.org",
    "Research email; pitch federal contracting member benefit"),

  c("e-018", "Tier 2", "WOSB Association",
    "Women Impacting Public Policy (WIPP)", "Operations",
    "LaTonia Pouncey", "Senior staff",
    "", "", "",
    "https://www.wipp.org/",
    "Washington, DC", "$50K-$100K",
    "Mentioned in recent WBENC NY DMV summit coverage as visible WIPP leadership figure.",
    "Branden",
    "Supporting cast.",
    "wbecnydmv.org",
    "Cc on Waterman outreach"),

  // ─── Trade Associations ───
  c("e-019", "Tier 1", "Trade Association",
    "AFCEA International", "HQ",
    "Lt. Gen. Susan S. Lawrence (Ret.)", "Outgoing President & CEO (until June 2026)",
    "", "", "",
    "https://www.afcea.org/",
    "Fairfax, VA", "$100K+",
    "BREAKING TIMING: Bruce Crawford incoming as 12th CEO June 2026. First African American to lead AFCEA. Lawrence retiring. Perfect inflection: pitch a 'new chapter' partnership as he takes over. 30,000 members across military/govt/industry — strongest C4ISR/defense IT trade association in country.",
    "Eric",
    "FLAGGED: Pitch the transition. Email Crawford via AFCEA after June 15 effective date.",
    "globenewswire.com (Apr 2026)",
    "TIMING WINDOW: Lawrence retiring June 2026 — pitch incoming CEO"),

  c("e-020", "Tier 1", "Trade Association",
    "AFCEA International", "Incoming CEO",
    "Lt. Gen. Bruce Crawford (Ret.)", "Incoming President & CEO (eff. June 15, 2026)",
    "", "", "",
    "https://www.afcea.org/",
    "Fairfax, VA", "$100K+",
    "Currently AFCEA Vice Chair (since May 2025), Budget & Finance Committee Chair. Becoming 12th AFCEA CEO June 2026. 'New leader, new partnership' framing is wide open. Army Lt. Gen. retired.",
    "Eric",
    "DATE-DEPENDENT: Hold outreach until 6/15/26 effective date.",
    "globenewswire.com",
    "Send welcome / partnership intro AFTER June 15"),

  c("e-021", "Tier 2", "Trade Association",
    "NCMA (National Contract Management Association)", "Board of Advisors",
    "Various", "Board of Advisors (80 senior executives)",
    "", "", "",
    "https://ncmahq.org/",
    "Ashburn, VA", "$50K-$100K",
    "Contract management profession HQ. Board includes Booz Allen, Raytheon, IBM, SAIC, Parsons heads of contracts. NCMA conferences attract every federal CO and KO. Need to ID named CEO.",
    "Branden",
    "Different angle — they manage contracts vs. find them. Soft fit. Lower priority.",
    "ncmahq.org",
    "Identify CEO name; pitch contract management vertical"),

  // ─── Tribal 8(a) ───
  c("e-022", "Tier 1", "Tribal 8(a)",
    "Native American Contractors Association (NACA)", "HQ",
    "Quinton Carroll", "Executive Director",
    "", "", "",
    "https://nativecontractors.org/",
    "Washington, DC", "$100K+",
    "Inupiat Community of Arctic Slope tribal member. Represents Tribes, ANCs, Native Hawaiian Orgs nationally. $23.3B in tribal federal contracts in 2023 (16% YoY surge). ANCs lead with 2/3 of the increase. Sole-source 8(a) cap raised from $20M to $100M. Massive market.",
    "Eric",
    "Cultural sensitivity required — refer to Eric for relationship approach.",
    "nativecontractors.org / indianz.com",
    "Research email; pitch member-benefit / federal intel"),

  c("e-023", "Tier 1", "Tribal 8(a)",
    "Native American Contractors Association (NACA)", "Co-Chair",
    "Katherine Carlton", "Co-Chair NACA / SVP Chugach Corporation",
    "", "", "",
    "https://nativecontractors.org/",
    "Anchorage, AK", "$100K+",
    "Chugach shareholder. Harvard B-School AMP. Oversees ANCSA lands & community development. Strong technical + business leader.",
    "Eric",
    "Pair with Quinton Carroll outreach.",
    "nativecontractors.org",
    "LinkedIn intro; reference Chugach federal work"),

  c("e-024", "Tier 1", "Tribal 8(a)",
    "Native American Contractors Association (NACA)", "Co-Chair",
    "Jon Deacon Panamaroff", "Co-Chair NACA / CEO Command Holdings (Pequot Co.)",
    "", "", "",
    "https://nativecontractors.org/",
    "Washington, DC area", "$100K+",
    "CEO of Command Holdings (Pequot tribe company). Hosted SBA Administrator Guzman fireside at NACA conf. Sitting at the table with federal leadership.",
    "Eric",
    "High-influence executive; warm introduction preferred over cold.",
    "linkedin.com/company/native-american-contractors-association",
    "LinkedIn intro; reference Command Holdings federal work"),

  c("e-025", "Tier 2", "Tribal 8(a)",
    "Alaska Native Village Corporation Association (ANVCA)", "HQ",
    "Shyanne Beatty", "Communications Consultant (entry point)",
    "shyanne@anvca.biz", "", "",
    "https://anvca.biz/",
    "Anchorage, AK", "$75K-$150K",
    "176 village corporations + 12 regional corporations. Annual symposium = audience of federal-contracting CEOs. Shyanne Beatty (comms consultant) is named, accessible contact for routing.",
    "Branden",
    "Massive aggregate market but requires cultural-fit care.",
    "anvca.biz / linkedin",
    "Email Shyanne Beatty for routing"),

  // ─── Existing customers ───
  c("e-026", "Tier 1", "Existing Customer",
    "Encore Funding", "Existing relationship",
    "", "Founder / CEO",
    "", "", "", "",
    "TBD", "$75K-$100K",
    "EXISTING: Per memo, contributing to $11,767/mo revenue together w/ White Glove. Already paying near enterprise pricing. Expansion opp: add-on services, more seats, custom briefing development. Don't re-sell — UPSELL.",
    "Eric",
    "Eric owns the relationship. Reference memo for revenue context.",
    "Mindy Enterprise.docx",
    "Schedule quarterly expansion review"),

  c("e-027", "Tier 1", "Existing Customer",
    "White Glove Client", "Existing relationship",
    "", "Decision-maker",
    "", "", "", "",
    "TBD", "$75K-$100K",
    "EXISTING: Co-contributor to $141K/yr revenue base. Same upsell logic as Encore.",
    "Eric",
    "Eric owns. Real org name redacted in memo.",
    "Mindy Enterprise.docx",
    "Schedule quarterly expansion review"),

  // ─── Channel ───
  c("e-028", "Channel", "Channel Partner",
    "[GovCon consulting firms — research list]", "Multiple",
    "", "Founding partners",
    "", "", "", "",
    "Various", "Referral",
    "Channel play: consultants/lawyers/CPAs whose clients all need MI. They become referral partners. Revenue share or affinity discount. Lower priority than direct enterprise sales but compounds over time.",
    "Branden",
    "Long-term play. Build list once direct pipeline is moving.",
    "Mindy Enterprise.docx",
    "Build target list of 10-15 boutique GovCon consultancies"),
];

// Mark existing customers as Nurture from the start
SEED_CONTACTS.forEach(c => {
  if (c.category === "Existing Customer") c.status = "Nurture";
});
